comment: false
github_checks: false
coverage:
  status:
    project: off
    # shows the coverage of the changed lines, without failing a pull request
    patch:
      default:
        informational: true
