// Symbol vocabulary of the serialization format: the canonical index <-> name
// mapping shared by the codec (GeoJSON `symbol-pattern`) and the editor (which
// adds sprite/offset rendering data on top). Kept asset-free so the codec stays
// independent of the editor.

export type SymbolEntry = [number, string, string?, [number, number]?];

export const symbolEntries: SymbolEntry[] = [
	[0, 'none'],
	[1, 'airplane', 'base:icon-airfield'],
	[2, 'airport', 'base:icon-airport'],
	[3, 'alcohol shop', 'base:icon-alcohol_shop'],
	[4, 'art gallery', 'base:icon-art_gallery'],
	[5, 'artwork', 'base:icon-artwork'],
	[6, 'atm', 'base:icon-atm'],
	[7, 'bakery', 'base:icon-bakery'],
	[8, 'bank', 'base:icon-bank'],
	[9, 'beauty', 'base:icon-beauty'],
	[10, 'beer', 'base:icon-beer_mug'],
	[11, 'beergarden', 'base:icon-pint_glass'],
	[12, 'bench', 'base:icon-bench'],
	[13, 'beverages', 'base:icon-beverages'],
	[14, 'bicycle share', 'base:icon-bicycle_share'],
	[15, 'books', 'base:icon-books'],
	[16, 'bus', 'base:icon-bus'],
	[17, 'butcher', 'base:icon-butcher'],
	[18, 'cafe', 'base:icon-cafe', [2, 0]],
	[19, 'car rental', 'base:icon-car_rental'],
	[20, 'car wash', 'base:icon-car_wash'],
	[21, 'castle', 'base:icon-castle'],
	[22, 'cemetery', 'base:icon-cemetery'],
	[23, 'chalet', 'base:icon-chalet'],
	[24, 'chemist', 'base:icon-tube_and_toothbrush'],
	[25, 'cinema', 'base:icon-cinema'],
	[26, 'clothes', 'base:icon-clothes'],
	[27, 'college', 'base:icon-college'],
	[28, 'community', 'base:icon-community'],
	[29, 'defibrillator', 'base:icon-defibrillator'],
	[30, 'doctor', 'base:icon-doctor'],
	[31, 'dog park', 'base:icon-dog'],
	[32, 'doityourself', 'base:icon-do_it_yourself'],
	[33, 'drinking water', 'base:icon-drinking_water'],
	[34, 'drycleaning', 'base:icon-dry_cleaning'],
	[35, 'emergency phone', 'base:icon-emergency_phone'],
	[36, 'fast food', 'base:icon-fast_food'],
	[37, 'fire station', 'base:icon-fire_station'],
	[38, 'flag', 'base:icon-embassy', [0, 0]],
	[39, 'florist', 'base:icon-florist'],
	[40, 'fountain', 'base:icon-fountain'],
	[41, 'furniture', 'base:icon-furniture'],
	[42, 'garden centre', 'base:icon-garden_center'],
	[43, 'gift', 'base:icon-gift'],
	[44, 'glasses', 'base:icon-optician'],
	[45, 'golf', 'base:icon-golf'],
	[46, 'greengrocer', 'base:icon-greengrocer'],
	[47, 'hardware', 'base:icon-hardware'],
	[48, 'hospital', 'base:icon-hospital'],
	[49, 'huntingstand', 'base:icon-hunting_stand'],
	[50, 'hydrant', 'base:icon-hydrant'],
	[51, 'icerink', 'base:icon-ice_rink'],
	[52, 'information', 'base:transport-information'],
	[53, 'jewelry store', 'base:icon-ring'],
	[54, 'kiosk', 'base:icon-newsagent'],
	[55, 'laundry', 'base:icon-laundry'],
	[56, 'letter', 'base:icon-post'],
	[57, 'library', 'base:icon-library'],
	[58, 'lighthouse', 'base:icon-lighthouse'],
	[59, 'marketplace', 'base:icon-marketplace'],
	[60, 'money', 'base:icon-bar'],
	[61, 'monument', 'base:icon-monument'],
	[62, 'newsagent', 'base:icon-newsagent'],
	[63, 'nightclub', 'base:icon-nightclub'],
	[64, 'nursinghome', 'base:icon-nursing_home'],
	[65, 'observation tower', 'base:icon-observation_tower'],
	[66, 'outdoor', 'base:icon-outdoor'],
	[67, 'pharmacy', 'base:icon-pill'],
	[68, 'picnic site', 'base:icon-picnic_site'],
	[69, 'place of worship', 'base:icon-person_kneeling_and_praying'],
	[70, 'playground', 'base:icon-seesaw'],
	[71, 'police', 'base:icon-police_officer', [-1, -3]],
	[72, 'postbox', 'base:icon-postbox'],
	[73, 'prison', 'base:icon-prison'],
	[74, 'rail light', 'base:transport-tram'],
	[75, 'rail metro', 'base:icon-rail'],
	[76, 'rail', 'base:icon-rail'],
	[77, 'recycling', 'base:icon-recycling'],
	[78, 'restaurant', 'base:icon-restaurant'],
	[79, 'run', 'base:icon-pitch'],
	[80, 'school', 'base:icon-school'],
	[81, 'scissor', 'base:icon-scissors_and_comb'],
	[82, 'shield', 'base:icon-historic', [0, -10]],
	[83, 'shoes', 'base:icon-shoes', [-5, 0]],
	[84, 'shop', 'base:icon-shop'],
	[85, 'shrine', 'base:icon-shrine'],
	[87, 'sports', 'base:icon-sports'],
	[88, 'stadium', 'base:icon-stadium'],
	[89, 'stationery', 'base:icon-stationery'],
	[90, 'surveillance', 'base:icon-surveillance'],
	[91, 'swimming', 'base:icon-swimming'],
	[92, 'telephone', 'base:icon-telephone'],
	[93, 'theatre', 'base:icon-theater'],
	[94, 'toilet', 'base:icon-restrooms'],
	[95, 'tooth', 'base:icon-dentist'],
	[96, 'town hall', 'base:icon-town_hall'],
	[97, 'toys', 'base:icon-rocking_horse'],
	[98, 'tram', 'base:transport-tram'],
	[99, 'travel agent', 'base:icon-travel_agent'],
	[100, 'vendingmachine', 'base:icon-vending_machine'],
	[101, 'veterinary', 'base:icon-veterinary'],
	[102, 'video', 'base:icon-video'],
	[103, 'viewpoint', 'base:icon-viewpoint', [0, -6]],
	[104, 'waste basket', 'base:icon-waste_basket'],
	[105, 'watermill', 'base:icon-watermill'],
	[106, 'waterpark', 'base:icon-water_park'],
	[107, 'windmill', 'base:icon-windmill'],
	[108, 'zoo', 'base:icon-zoo']
];

const nameByIndex = new Map<number, string>(symbolEntries.map(([index, name]) => [index, name]));
const indexByName = new Map<string, number>(symbolEntries.map(([index, name]) => [name, index]));

/** Name of the symbol with the given index, or undefined if unknown. */
export function symbolName(index: number): string | undefined {
	return nameByIndex.get(index);
}

/** Index of the symbol with the given name, or undefined if unknown. */
export function symbolIndexByName(name: string): number | undefined {
	return indexByName.get(name);
}
